"""
Global constants and calibrated parameters for the BENCH model.
Combines structural configuration with behavioural rates and thresholds.
"""

import numpy as np

# ---------------------------------------------------------------------------
# Model configuration
# ---------------------------------------------------------------------------

MODEL_START_YEAR = 2015
MODEL_END_YEAR = 2030
TIMESTEP_YEARS = 1
NUMBER_SEED_RUNS = 10

VERBOSE = False

# Income Groups (7 groups)
INCOME_GROUPS = list(range(1, 8))

# Dwelling Energy Labels (A-F = 1-6)
DWELLING_LABELS = list(range(1, 7))
DWELLING_LABEL_NAMES = ['A', 'B', 'C', 'D', 'E', 'F']

# ---------------------------------------------------------------------------
# Energy source flags
# ---------------------------------------------------------------------------

FLAG_GRAY = 0
FLAG_BROWN = 1
FLAG_GREEN = 2
FLAG_NAMES = {0: 'gray', 1: 'brown', 2: 'green'}

# ---------------------------------------------------------------------------
# Behavioural scale
# ---------------------------------------------------------------------------

BEHAVIORAL_SCALE_MIN = 0
BEHAVIORAL_SCALE_MAX = 7
BEHAVIORAL_SCALE_GUILT_THRESHOLD = 5.21   # guilt activates at this awareness level
BEHAVIORAL_CAP = 6.5                       # norm/awareness variables cap here

PBC_MIN = 0
PBC_MAX = 7
PBC_THRESHOLD = 4

# ---------------------------------------------------------------------------
# Delta (consideration factor) — PBC thresholds → delta values
# ---------------------------------------------------------------------------

DELTA_LEVELS = {
    0.2: (0, 2),
    0.3: (2, 3),
    0.4: (3, 4),
    0.5: (4, 5),
    0.6: (5, 6),
    0.7: (6, 7),
}

# ---------------------------------------------------------------------------
# Investment parameters
# ---------------------------------------------------------------------------

INVESTMENT_PV_PAYBACK_YEARS = 10
INVESTMENT_PV_ANNUAL_COST = 487.59       # annual repayment cost (€)
INVESTMENT_PV_ENERGY_OUTPUT = 1700       # kWh/year generated by PV

# ---------------------------------------------------------------------------
# Conservation parameters
# ---------------------------------------------------------------------------

CONSERVATION_RATE = 0.5                  # fraction of h_q saved per conservation action
CONSERVATION_MIN_KWH = 1000.0            # floor: agent becomes HH_EFFICIENT below this

# ---------------------------------------------------------------------------
# Action cooldown durations (years)
# ---------------------------------------------------------------------------

CONSERVATION_COOLDOWN_YEARS = 5
SWITCH_COOLDOWN_YEARS = 2

# ---------------------------------------------------------------------------
# Emission factors (kg CO2 per kWh)
# ---------------------------------------------------------------------------

# For total-emissions accounting (statistics.py)
EMISSIONS_FACTOR_GRAY = 0.5
EMISSIONS_FACTOR_BROWN = 0.3
EMISSIONS_FACTOR_GREEN = 0.0
KG_TO_TONS = 0.001

# For emissions-avoided accounting (vectorized.py)
CO2_FACTOR_GREY = 0.9
CO2_FACTOR_BROWN = 0.3

# ---------------------------------------------------------------------------
# Responsibility thresholds per case study
# (per_nab_thresh, su_nor_thresh) for [INV, CON, SWI]
# ---------------------------------------------------------------------------

RESPONSIBILITY_THRESHOLDS = {
    "Spain-Navarre": (
        np.array([5.67, 5.40, 5.78]),
        np.array([4.77, 4.45, 5.05]),
    ),
    "Netherlands-Overijssel": (
        np.array([5.67, 5.40, 5.78]),
        np.array([4.45, 3.66, 5.05]),
    ),
}

# ---------------------------------------------------------------------------
# Social learning rates
# ---------------------------------------------------------------------------

LEARN_AWARENESS_RATE_FAST = 1.05
LEARN_AWARENESS_RATE_SLOW = 1.02
LEARN_PER_NAB_PBC_RATE = 1.05
LEARN_SU_NOR_RATE = 1.07
SLOW_LEARN_MIN_NEIGHBORS = 2     # minimum neighbours required for slow-adaptation to fire
SLOW_LEARN_NUM_NEIGHBORS = 2     # number of neighbours sampled per actor in slow adaptation

# ---------------------------------------------------------------------------
# Regret rates
# ---------------------------------------------------------------------------

REGRET_PER_NAB_PBC_RATE = 0.95
REGRET_SU_NOR_RATE = 0.97

# ---------------------------------------------------------------------------
# Carbon-price awareness rates (cpinfo), keyed by policy string
# ---------------------------------------------------------------------------

CPINFO_RATES = {
    "Carbon price pressure-10": {
        "awareness": 1.01,
        "su_nor":    None,
        "pbc":       None,
    },
    "Carbon price pressure-25": {
        "awareness": 1.02,
        "su_nor":    1.04,
        "pbc":       1.03,
    },
    "Carbon price pressure-50": {
        "awareness": 1.04,
        "su_nor":    1.06,
        "pbc":       1.04,
    },
    "Carbon price pressure-100": {
        "awareness": 1.06,
        "su_nor":    1.10,
        "pbc":       1.05,
    },
}

# ---------------------------------------------------------------------------
# CGE data column per income group (groups 5-7 share the same column)
# ---------------------------------------------------------------------------

CGE_INCOME_GROUP_COLS = {1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 4, 7: 4}

# ---------------------------------------------------------------------------
# Case study / scenario / policy / learning type enumerations
# ---------------------------------------------------------------------------

CASE_STUDIES = ["Netherlands-Overijssel", "Spain-Navarre"]
SCENARIOS = ["Ref_SSP2"]
POLICIES = [
    "Ref",
    "Carbon price pressure-10",
    "Carbon price pressure-25",
    "Carbon price pressure-50",
    "Carbon price pressure-100",
]
CARBON_POLICY_TARGETS = {
    "Ref": 0.0,
    "Carbon price pressure-10": 10.0,
    "Carbon price pressure-25": 25.0,
    "Carbon price pressure-50": 50.0,
    "Carbon price pressure-100": 100.0,
}
LEARNING_TYPES = [
    "No learning",
    "Fast adaptation",
    "Slow adaptation",
]
DEFAULT_LEARNING_TYPE = "No learning"

# ---------------------------------------------------------------------------
# Base energy prices (€/kWh)
# ---------------------------------------------------------------------------

M_P_GREY_BASE = 0.15
M_P_BROWN_BASE = 0.15
M_P_GREEN_BASE = 0.15

# ---------------------------------------------------------------------------
# File paths (relative to project root)
# ---------------------------------------------------------------------------

DATA_DIR = "data"
HOUSEHOLD_FILE = "data/household.csv"
CGE_NL_CON_FILE = "data/cge-nl-ssp2-con.csv"
CGE_NL_H_FILE = "data/cge-nl-ssp2-h.csv"
CGE_NL_ALPHA_FILE = "data/cge-nl-ssp2-alpha.csv"
PRIMES_NL_PRICES_FILE = "data/primes-nl-ref-prices.csv"
PRIMES_NL_CON_FILE = "data/primes-nl-ref-con.csv"
PRIMES_NL_NONCON_FILE = "data/primes-nl-ref-noncon.csv"
PRIMES_SPN_PRICES_FILE = "data/primes-spn-ref-prices.csv"

# ---------------------------------------------------------------------------
# Output configuration
# ---------------------------------------------------------------------------

OUTPUT_DIR = "output"
OUTPUT_HOUSEHOLD_FILE = "annual_household_data.csv"
OUTPUT_AGGREGATES_FILE = "annual_aggregates.csv"
OUTPUT_ACTIONS_FILE = "actions_breakdown.csv"

# ---------------------------------------------------------------------------
# Utility normalisation
# ---------------------------------------------------------------------------

UTILITY_NORMALIZATION_FACTOR = 0.5   # alpha: weight of economic vs behavioural utility

# ---------------------------------------------------------------------------
# Memory recall probabilities by income group and energy flag
# ---------------------------------------------------------------------------

GUILT_LOW = 'L'
GUILT_HIGH = 'H'
ACTIONS = ['investment', 'conservation', 'switching']

MEMORY_RULES = {
    1: {
        1: {
            'act11': (0.5714, True),
            'act31': (0.1428, True),
            'act32': (0.8572, True),
            'act21': (0.2143, True),
        },
        0: {
            'act12': (0.5814, True),
            'act40': (0.0930, True),
        }
    },
    2: {
        1: {
            'act11': (0.7829, True),
            'act31': (0.1513, True),
            'act32': (0.8487, True),
            'act21': (0.1710, True),
        },
        0: {
            'act12': (0.6860, True),
            'act40': (0.0870, True),
        }
    },
    3: {
        1: {
            'act11': (0.8240, True),
            'act31': (0.1410, True),
            'act32': (0.8590, True),
            'act21': (0.1700, True),
            'always_act2': (1.0000, True),
        },
        0: {
            'act12': (0.8048, True),
            'act40': (0.1155, True),
        }
    },
    4: {
        1: {
            'act11': (0.8310, True),
            'act31': (0.1846, True),
            'act32': (0.8154, True),
            'act21': (0.1846, True),
        },
        0: {
            'act12': (0.4286, True),
            'act40': (0.1600, True),
        }
    },
    5: {
        1: {
            'act11': (0.8847, True),
            'act31': (0.2310, True),
            'act32': (0.7690, True),
            'act21': (0.2310, True),
        },
        0: {
            'act12': (0.8789, True),
            'act40': (0.1818, True),
        }
    },
    6: {
        1: {
            'always_act11': (1.0000, True),
            'act31': (0.5000, True),
            'act32': (0.5000, True),
            'act21': (0.50)
        },
        0: {
            'always_act12': (1.0000, True),
            'act40': (0.2500, True),
        }
    },
    7: {
        1: {
            'act11': (0.6000, True),
            'act31': (0.2000, True),
            'act32': (0.8000, True),
            'act21': (0.2000, True),
        },
        0: {
            'act12': (0.8333, True),
            'act40': (0.0830, True),
        }
    }
}
